name: Test Bundle

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          # Install MCPB tool globally
          npm install -g @anthropic-ai/mcpb

          # Install project dependencies
          npm ci

      - name: Build project
        run: |
          npm run build

      - name: Test MCP Bundle creation
        run: |
          # Test bundle creation with official mcpb tool
          mcpb pack .

      - name: Verify bundle
        run: |
          # Verify bundle file exists
          if [ -f "adsb-mcp-server.mcpb" ]; then
            echo "✅ Bundle file created successfully"
            ls -la adsb-mcp-server.mcpb

            # Check bundle size
            BUNDLE_SIZE=$(stat -c%s "adsb-mcp-server.mcpb")
            echo "Bundle size: $BUNDLE_SIZE bytes"

            # Verify contents
            echo "Bundle contents:"
            unzip -l adsb-mcp-server.mcpb

            # Verify manifest exists
            if unzip -l adsb-mcp-server.mcpb | grep -q "manifest.json"; then
              echo "✅ Manifest found in bundle"
            else
              echo "❌ Manifest not found in bundle"
              exit 1
            fi

            # Verify compiled JavaScript exists
            if unzip -l adsb-mcp-server.mcpb | grep -q "dist/src/readsb_mcp_server.js"; then
              echo "✅ Compiled server found in bundle"
            else
              echo "❌ Compiled server not found in bundle"
              exit 1
            fi

          else
            echo "❌ Bundle file not created"
            exit 1
          fi

      - name: Clean up
        run: |
          rm -f adsb-mcp-server.mcpb
